### ISSUE TITLE
Rename the asciidoc file to book.asciidoc

### ISSUE THREAD

**Issue by rdhyee** [GITenberg/Adventures-of-Huckleberry-Finn_76#13]
As a specific case for https://github.com/gitenberg-dev/Second-Folio/issues/9, should https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/master/Adventures-of-Huckleberry-Finn.asciidoc be renamed `book.asciidoc`?  And then https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/master/.travis.yml be changed (replacing all specific names to a the generic book.asciidoc, book.epub, book.html?)

**Comment by sethwoodworth** [comment]
Yes, absolutely.  `book.asciidoc`, `book.html`  If we can manage it, it would be nice to make the final epub file be `Adventures-of-Huckleberry-Finn.epub`. Let me add that as a task for `gitberg`

**Comment by eshellman** [comment]
Appears to be done

**Comment by rdhyee** [comment]
yes
