### ISSUE TITLE
metadata.yaml not in sync with latest output from write_yaml

### ISSUE THREAD

**Issue by rdhyee** [GITenberg/Adventures-of-Huckleberry-Finn_76#17]
About the Huck Finn metadata -- see diff: https://gist.githubusercontent.com/rdhyee/b6326d2da39501cd610d/raw/ef77a3fb8964d1d1cf02615e43f9f1b4978432bd/huck_meta_diff.txt 

I think the Huck Finn metadata.yaml in the db reflects output from previous version of Eric's code....Can @eshellman  make sure https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/master/metadata.yaml is ok given the evolution of yaml coming out of his code?

The gist where I run sdiff between the output of the latest write_yaml and metadata.yaml currently in the Huck Finn repo is https://gist.github.com/rdhyee/b6326d2da39501cd610d

**Comment by eshellman** [comment]
how were these files generated?

**Comment by eshellman** [comment]
yaml in the db is missing _repo

**Comment by rdhyee** [comment]
left column: latest output from running https://github.com/rdhyee/giten_site/blob/4723eb8b1e71b64f41cc078f4936a06bd9343bcc/gitensite/apps/bookinfo/management/commands/write_yaml.py for book_id=76

right column: https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/523211d566fd0d9fef72b397cd68f080a65dfc1a/metadata.yaml

**Comment by eshellman** [comment]
how was  https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/master/metadata.yaml  created generated?

**Comment by rdhyee** [comment]
@Eric -- see history of the file: https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/commits/master/metadata.yaml  --> the very first file presumably came from you...and then we've making tweaks by hand.

**Comment by eshellman** [comment]
file updated with PR#18
